OnlineEXP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from events.views import notes
from user_account.urls import *
# import tinymce
urlpatterns =urlpatterns+ [
path('admin/', admin.site.urls),
path('', include('user_account.urls')),
path('', include('events.urls')),
# path('summernote/', include('django_summernote.urls')),
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'OnlineEXP'

events/urls.py
from django.urls import path, include 
from django.conf.urls import url
from events import views
# todo lo de aqui es tentativo por que quiza no comprendo bien el enlazamiento de las entidades
urlpatterns = [ 
    path('legal/<slug>/', views.legal, name='legal'),
    path('privacy/<slug>/', views.privacy, name='privacy'),

    path('legal/', views.legal, name='legal'),
    path('privacy/', views.privacy, name='privacy'),

    # path('notes/',views.notes,name='notes'),
    # path('notes/<str:title>',views.edit_note,name='notes'), 
    # path('notes/delete/<str:title>',views.delete_note,name='delete_note'), 


    # path('support/', views.support,name='support'),
    # path('event/',views.all_events,name='all_events'),
    # path('event/<str:name_event>/',views.event,name='event'),
    # path('event/unregistry/<str:name_event>', views.unregistry_event, name='unregistry_event'),
    # path('event/join/<str:name_event>', views.join_event, name='join_event'),

    path('event/<str:slug>/', views.see_event, name='see_event'),
    path('event/<str:slug>/support', views.support, name='support'),
    # indica la subvista a usar, room o notes etc...
    # aqui no funciona el generico, no funciona el chat
    # path('event/<str:name_event>/<str:token>', views.event_nested_views, name='event_ne'),

    path('event/programm/<slug>/', views.programa  , name='programa'), 
    path('event/resources/<slug>/', views.recursos  , name='recursos'), 

    # las url de abajo tiene un valor si devuelve todos y dos valores si devuelve un solo room o anuncio
    # es como el get_object y el get_list, se encesitan las url por el parametro
    path('event/room/<slug>/', views.rooms, name='rooms'),

    # principal
    path('event/room/<slug>/<slug_room>', views.room    , name='room'),

    # no funcionan? creo que  por que no existen anuncios
    # path('event/announcements/<str:name_event>/', views.anuncios  , name='anuncios'),
    # path('event/announcements/<str:name_event>/<str:name_ann>/', views.anuncios  , name='anuncios'), 

    path('event/speaker/<slug>/', views.speaker  , name='speakers'), 
    path('event/speaker/<slug>/<slug_speak>/', views.speaker  , name='speakers'), 

    path('event/notes/<slug>/', views.notes  , name='notes'), 
    path('event/notes/<slug>/<str:title>/',views.edit_note,name='notes'), 
    path('event/notes/<slug>/delete/<str:title>/',views.delete_note,name='delete_note'), 


    # esta vista es necesaria para crear los pdfs aunque nunca se acceda a ella!! no borrar!
    path('notes/pdf/<str:title>', views.create_pdf, name='create_pdf'), 
    path('event/<slug>/user-guide', views.user_guide, name='user_guide'), 
    path('event/sponsors/<slug>/', views.sponsors  , name='sponsors'), 
    path('event/peticiones_oracion/<slug>/', views.supportspiritual  , name='supportspiritual'), 
    path('event/teamedition/<slug>/', views.teamedition  , name='teamedition'), 


]

events/models.py
from django.db import models
from django_countries.fields import CountryField
from colorfield.fields import ColorField
from django.utils import timezone
from django.utils.timezone import now
from user_account.models import Code, License
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


class Client(models.Model):
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default='my_name')
    picture = models.FileField(upload_to='pictures/', blank=True, null=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default='my_name')
    client = models.ForeignKey(Client, related_name='event_client', on_delete=models.CASCADE, blank=True,
                               null=True)  # default=1)
    start_date = models.DateField(default=now)
    end_date = models.DateField(default=now)  # date += datetime.timedelta(days=1)
    language = models.CharField(max_length=149, blank=True, null=True)
    country = CountryField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    event_logo = models.FileField(upload_to='pictures/', blank=True, null=True)
    event_banner_1 = models.FileField(upload_to='pictures/', blank=True, null=True)
    event_banner_2 = models.FileField(upload_to='pictures/', blank=True, null=True)
    have_live_player = models.BooleanField(default=False)
    have_chat = models.BooleanField(default=False)
    code = models.ForeignKey(Code, related_name='event_code', on_delete=models.CASCADE, blank=True, null=True,
                             default=None)
    license = models.ForeignKey(License, related_name='event_license', on_delete=models.CASCADE, blank=True, null=True,
                                default=None)

    # colorfield pip install django colorfield

    brand_color_1 = ColorField(default='#6F2EFF')
    brand_color_2 = ColorField(default='#6F2EFF')
    brand_color_3 = ColorField(default='#6F2EFF')

    def _get_unique_slug(self):
        slug_string = self.name
        slug = slugify(slug_string)
        unique_slug = slug
        num = 1
        while Category.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Event_User(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.event.name + '---' + self.user.username)


# class Landing(models.Model):	
# 		client = models.ForeignKey(Event, related_name='landing_event',on_delete=models.CASCADE, blank=True, null=True)#default=1)
# def __str__(self):
# 	return self.name

class LivePlayer(models.Model):
    event = models.ForeignKey(Event, related_name='liveplayer_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    typess = (
        (1, "Live"),
        (2, "SimulatedLive"),
        (3, "VideoPlaceholder"),
    )

    type_video = models.PositiveSmallIntegerField(choices=typess, default=1)
    live_video = models.TextField(blank=True, null=True)
    simulated_live = models.TextField(blank=True, null=True)
    simulated_live_start = models.DateTimeField(default=now)
    simulated_live_ends = models.DateTimeField(default=now)
    placeholder_video = models.TextField(blank=True, null=True)
    use_live_video = models.BooleanField(default=False)
    use_simulated_live = models.BooleanField(default=False)
    use_placeholder_video = models.BooleanField(default=False)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)

    # si necesitas pasar el valor de type_video a los templates usar {instanciaLivePlayer.type_value}
    def type_value(self):
        return dict(LivePlayer.typess)[self.type_video]

    def __str__(self):
        return str(self.event.name + "-" + str(self.type_value()))


class Chat(models.Model):
    event = models.ForeignKey(Event, related_name='chat_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    embed_code = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.event.name


class Schedule(models.Model):
    event = models.ForeignKey(Event, related_name='schedule_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.event.name


class Announcement(models.Model):
    event = models.ForeignKey(Event, related_name='announcement_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    name = models.CharField(max_length=149, unique=True)
    # slug = models.SlugField(max_length=149, default='my_name')
    horizontal_banner = models.FileField(upload_to='pictures/', blank=True, null=True)
    horizontal_banner_title = models.CharField(max_length=149, blank=True, null=True)
    horizontal_banner_link = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    vertical_banner = models.FileField(upload_to='pictures/', blank=True, null=True)
    vertical_banner_title = models.CharField(max_length=149, blank=True, null=True)
    vertical_banner_link = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    link_1 = models.URLField(max_length=200, default='https://google.com')
    link_title_1 = models.CharField(max_length=149, blank=True, null=True)
    link_2 = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    link_title_2 = models.CharField(max_length=149, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    # def _get_unique_slug(self):
    # 	slug_string = self.name
    # 	slug = slugify(slug_string)
    # 	unique_slug = slug
    # 	num = 1
    # 	while Category.objects.filter(slug=unique_slug).exists():
    # 		unique_slug = '{}-{}'.format(slug, num)
    # 		num += 1
    # 	return unique_slug

    # def save(self, *args, **kwargs):
    # 	if not self.slug:
    # 		self.slug = self._get_unique_slug()
    # 	super().save(*args, **kwargs)
    def __str__(self):
        return self.name


class Resource(models.Model):
    event = models.ForeignKey(Event, related_name='resource_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    title = models.CharField(max_length=149, unique=True)
    link = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class Room(models.Model):
    event = models.ForeignKey(Event, related_name='room_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default=None)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)
    banner = models.FileField(upload_to='pictures/', blank=True, null=True)
    icon = models.CharField(max_length=149, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    own_chat = models.BooleanField(default=False)
    own_liveplayer = models.BooleanField(default=False)
    chat = models.TextField(blank=True, null=True)
    live_video = models.TextField(blank=True, null=True)
    simulated_live = models.TextField(blank=True, null=True)
    simulated_live_start = models.DateTimeField(default=now)
    simulated_live_ends = models.DateTimeField(default=now)
    placeholder_video = models.TextField(blank=True, null=True)
    use_live_video = models.BooleanField(default=False)
    use_simulated_live = models.BooleanField(default=False)
    use_placeholder_video = models.BooleanField(default=False)

    def _get_unique_slug(self):
        slug_string = self.name
        slug = slugify(slug_string)
        unique_slug = slug
        num = 1
        while Room.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Speaker(models.Model):
    event = models.ForeignKey(Event, related_name='speaker_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default=None)
    text = models.TextField(blank=True, null=True)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)

    def _get_unique_slug(self):
        slug_string = self.name
        slug = slugify(slug_string)
        unique_slug = slug
        num = 1
        while Speaker.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Video(models.Model):

events/forms.py
from events.models import *
from django import forms
# class NoteForm(forms.ModelForm):
# 	class Meta:
# 		model = Note
# 		fields ='__all__'
from ckeditor.widgets import CKEditorWidget
class NoteForm(forms.ModelForm):
	text = forms.CharField(widget=CKEditorWidget())
	class Meta:
		model = Note
		fields = '__all__'


from django.contrib.auth.models import User  

 

class SupportForm(forms.ModelForm): 
	# email=forms.CharField(max_length=128,  required=False, widget=forms.EmailInput())
	image=forms.FileField(max_length=128,  required=False, )
	class Meta():

		model = SpiritualSupportRequest
		fields = ('name',"description","image")


# from upload_validator import FileTypeValidator
from django.core.exceptions import ValidationError
def file_size(value):
    limit = 1 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 9 MiB.')


class TeamEditionForm(forms.ModelForm): 
	image=forms.FileField(  required=False)#,  validators=[file_size],)

	class Meta:
		model = Teamedition
		fields=["title","content","image"]
		# fields = '__all__'




# from django_summernote.fields import SummernoteTextFormField, SummernoteTextField

# from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

# # # # Apply summernote to specific fields.
# class NoteForm2(forms.Form):
#     foo = forms.CharField(widget=SummernoteWidget()) 


# class FormFromSomeModel(forms.ModelForm):
#     class Meta:
#         model = SomeModel
#         widgets = {
#             'foo': SummernoteWidget(),
#             'bar': SummernoteInplaceWidget(),
#         }

templates/spa/app/event/dashboard/speaker.html
{% extends './base/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %} Speaker {% endblock %}
{% block description %} La Cumbre Global del Liderazgo   {% endblock %}
{% block content %}
          <!--
          BEGINS CONTENT
          -->
          <!--
          ENDS CONTENT
          -->
{% endblock %}

templates/spa/app/event/dashboard/spiritualsupport.html
{% extends './base/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %} Peticion de Oración {% endblock %}
{% block description %} La Cumbre global del Liderazgo {% endblock %}
{% block content %}
<!--
BEGINS CONTENT
-->
    <!-- BEGINS floating player -->
    <div data-notify="container" class="alert alert-dismissible alert-info alert-notify animated fadeInDown" role="alert" data-notify-position="top-center"
         style=" display: inline-block; margin: 0px auto; position: fixed;
         transition: all 0.5s ease-in-out 0s; z-index: 1080;  animation-iteration-count: 1;
         max-width: 250px; right: 20px; bottom:10px; padding: 0; background-color: rgba(0,0,0,0.1);
         border-color: rgba(0,0,0,0.1)"
    >
        <span hidden class="alert-icon ni ni-bell-55" data-notify="icon"></span>
        <div class="alert-text" <="" div="">
        <span  class="alert-title" data-notify="title" style="width: 250px;"></span>
        <span data-notify="message">
            {% autoescape off %}
                {{ live.live_video }}
            {% endautoescape %}
        </span>
    </div>
    <button hidden type="button" class="close" data-notify="dismiss" aria-label="Close" style="position: absolute; right: 10px; top: 5px; z-index: 1082;">
        <span aria-hidden="true">x</span>
    </button>
    </div>
    <!-- ENDS floating player -->
<div class="container-fluid" style="margin-top: -20px">
	<div class="row">
		<div class="col-lg-12">

			<!-- BEGINS SUPPORT -->
			<div class="card" style="background-color: rgba(255,255,255,0.75);">
				<div class="card-header" style="padding-bottom: 0;">
					<div class="card-icon">
						<h4 class="card-title"><i class="material-icons" style="padding-right: 10px; font-size: 16px">pan_tool</i> PETICIONES DE ORACION</h4>
					</div>
				</div>
				<div class="card-body">
					<!-- BEGINS FORM -->
					<div class="container">
                        <div class="card-body text-justify" style="background-color: white; margin-bottom: 10px; padding-bottom: 10px;">
                            <p>
                                Por favor déjanos tus datos y envía a través de esta forma tu petición de oración, que será tratada de manera digna y respetuosa.
                            </p>
                        </div>
						{% if error_messages %} 
						<div class="alert alert-danger">
							<strong>{{ error_messages }}</strong>
						</div>  
						{% endif %} 
						{% if messages %} 
						<div class="alert alert-success">
							<strong>{{ messages }}</strong>
						</div>  
						{% endif %}
						<form enctype="multipart/form-data" method="POST" action="{% url 'supportspiritual' event.slug  %}">
							{% csrf_token %} 
							<!-- {{ form.as_p }} -->

							<!--    <p><label for="id_contact_email" class="col-md-2 col-form-label form-control-label">Email:</label><br>
							<input class="form-control" type="email" name="contact_email" maxlength="128" id="id_contact_email" required/></p> -->

							<p><label for="id_subject" class="col-md-2 col-form-label form-control-label">Nombre:</label> <br>
							<input class="form-control" type="text" name="name" maxlength="149" id="id_name" required /></p>

							<p><label for="id_description" class="col-md-2 col-form-label form-control-label">Mensaje:</label><br>

							<script type="text/javascript" src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
							<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
							<div class="django-ckeditor-widget" data-field-id="id_description" style="width: auto !important;">
								<textarea style="width: 100%;min-height: 75px;outline: none;resize: none;" id="id_description" name="description" rows="3"  data-processed="0"
								data-config="{&quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]],
								&quot;height&quot;: 200, &quot;toolbar&quot;: &quot;Full&quot;, &quot;skin&quot;: &quot;moono-lisa&quot;,
								&quot;language&quot;: &quot;en-us&quot;, &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;,
								&quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;,
								&quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [ &quot;Table&quot;, &quot;HorizontalRule&quot;],
								[&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;]], &quot;filebrowserWindowHeight&quot;: 725,
								&quot;filebrowserWindowWidth&quot;: 940}"
								data-external-plugin-resources="[]" data-id="id_description" data-type="ckeditortype"> </textarea>
							</div>
							<p>


							<!-- 
							<textarea class="form-control" name="description" rows="10" cols="40" id="id_description" value="" required></textarea></p> -->

							<p>
							<label for="id_file" class="col-md-2 col-form-label form-control-label">Fotografia:</label> <br>
							<input class="form-control" type="file" name="image" id="id_image" /></p>
                            <br>
							<button type="submit" class="save btn btn-default float-right">Enviar Petición de oración</button>
							<!-- <input type="submit" name="" value="Send Support Ticket" > -->
						</form>
					</div>
				</div> 
<!-- ENDS FORM -->
			</div>
		</div>
<!-- ENDS SUPPORT -->
	</div>
</div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
<!--
ENDS CONTENT
-->
{% endblock %}

templates/spa/app/event/dashboard/teamedition.html
{% extends './base/base.html' %}
{% load staticfiles %}
{% load widget_tweaks %}
{% block title %} Adquiere el Team Edition {% endblock %}
<!-- {% block description %}  {% endblock %} -->
{% block content %}
    <!-- Chromecast SDK -->
            <script type="text/javascript" src="//www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></script>
            <!-- THEOplayer library and css -->
            <script type="text/javascript" src="https://cdn.myth.theoplayer.com/591eb373-a225-467e-9960-bbb2f5db6342/THEOplayer.js"></script>
            <link rel="stylesheet" type="text/css" href="https://cdn.myth.theoplayer.com/591eb373-a225-467e-9960-bbb2f5db6342/ui.css" />
            <!-- Customization Theoplayer css styles -->
            <style>
                .theo-primary-color,
                .vjs-selected {
                    color: #ffffff !important;
                }
                .theo-primary-background {
                    color: #000000 !important;
                    background-color: #4a90e2 !important;
                }
                .theo-secondary-color {
                    color: #ffffff !important;
                }
                .theo-secondary-background {
                    color: #000000 !important;
                    background-color: #ffffff !important;
                }
                .theo-tertiary-color {
                    color: #000000 !important;
                }
                .theo-tertiary-background {
                    color: #ffffff !important;
                    background-color: #000000 !important;
                }
            </style>
          <!--
          BEGINS CONTENT
          -->
            <!-- BEGINS floating player -->
            <div data-notify="container" class="alert alert-dismissible alert-info alert-notify animated fadeInDown" role="alert" data-notify-position="top-center"
                 style=" display: inline-block; margin: 0px auto; position: fixed;
                 transition: all 0.5s ease-in-out 0s; z-index: 1080;  animation-iteration-count: 1;
                 max-width: 250px; right: 20px; bottom:10px; padding: 0; background-color: rgba(0,0,0,0.1);
                 border-color: rgba(0,0,0,0.1)"
            >
                <span hidden class="alert-icon ni ni-bell-55" data-notify="icon"></span>
                <div class="alert-text" <="" div="">
                <span  class="alert-title" data-notify="title" style="width: 250px;"></span>
                <span data-notify="message">
                    {% autoescape off %}
                        {{ live.live_video }}
                    {% endautoescape %}
                </span>
            </div>
            <button hidden type="button" class="close" data-notify="dismiss" aria-label="Close" style="position: absolute; right: 10px; top: 5px; z-index: 1082;">
                <span aria-hidden="true">x</span>
            </button>
            </div>
            <!-- ENDS floating player -->
<!--
BEGINS CONTENT
-->
<div class="container-fluid" style="margin-top: -20px">
	<div class="row">
		<div class="col-lg-12">

			<!-- BEGINS SUPPORT -->
			<div class="card" style="background-color: rgba(255,255,255,0.75);">
				<div class="card-header" style="padding-bottom: 0;">
					<div class="card-icon">
						<h4 class="card-title"><i class="fa fa-file" style="padding-right: 10px;"></i>Adquiere tu licencia del Team Edition</h4>
					</div>
				</div>
				<div class="card-body">
					<!-- BEGINS FORM -->

					<div class="container">
                        <div class="card-body" style="background-color: white; padding-bottom: 10px;">
                            <p>
                                    <center class="text-center">
                                    <span class="h3">Nos complace presentarles la nueva versión del <b>Team Edition</b></span>
                                    <br>
                                    <br>
                                    <a href="https://glsteamedition.com" target="_blank">
                                    <img class="img-fluid" style="max-height: 200px;" src="{% static 'assets/img/teamedition-web-preview.jpeg' %}">
                                    </a>
                                    <br>
                                    <br>
                                    Una aplicación de Video-OnDemand disponible para todas las plataformas.
                                    <br>
                                    Disfruta del contenido de la cumbre en tu Smartphone, Tablet y Computadora.
                                    </center>
                                    <br>
                                    Para adquirir tu licencia sigue los siguientes pasos:
                                    <br>
                                    <br>
                                    <b>1.</b>Realiza tu depósito o tranferencia por $1,000.00mn a la cuenta:
                                    <br>
                                    <br>
                                    <b>BANAMEX</b>
                                    <br>
                                    <b>Beneficiario:</b> Primera Iglesia Bautista de Ciudad Satélite AR
                                    <br>
                                    <b>Cuenta:</b> 101272
                                    <br>
                                    <b>Sucursal:</b> 4153
                                    <br>
                                    <b>Clabe Interbancaria:</b> 002180415301012721
                                    <br>
                                    <br>
                                    <b>2.</b> Reportar su depósito a través de esta forma, déjanos tus datos y adjunta la imagen o el documento del comprobante de pago.
                                    <br>
                                    Puedes enviar también un correo a <span class="text-primary">lucyere.garcia@prodigy.net.mx</span> con tus datos y la imagen o el documento del comprobante de pago. 
                                    <br>
                                    <br>
                                    <b>3.</b>  Si presentas dudas puedes llamar al teléfono: <b>55 3988 8077</b>
                            </p>
                        </div>
                        <br>
						{% if error_messages %} 
						<div class="alert alert-danger">
							<strong>{{ error_messages }}</strong>
						</div>  
						{% endif %} 
						{% if messages %} 
						<div class="alert alert-success">
							<strong>{{ messages }}</strong>
						</div>  
						{% endif %}
						<form enctype="multipart/form-data" method="POST" action="{% url 'teamedition' event.slug  %}">
							{% csrf_token %} 
							<!-- {{ form.as_p }} -->

							<!--    <p><label for="id_contact_email" class="col-md-2 col-form-label form-control-label">Email:</label><br>
							<input class="form-control" type="email" name="contact_email" maxlength="128" id="id_contact_email" required/></p> -->

							<p><label for="id_subject" class="col-md-2 col-form-label form-control-label">Nombre:</label> <br>
							<input class="form-control" type="text" name="title" maxlength="149" id="id_title" required /></p>

							<p><label for="id_content" class="col-md-2 col-form-label form-control-label">Mensaje:</label><br>

							<script type="text/javascript" src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
							<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
							<div class="django-ckeditor-widget" data-field-id="id_content" style="width: auto !important;">
								<textarea style="width: 100%;min-height: 75px;outline: none;resize: none;" id="id_content" name="content" rows="3"  data-processed="0"
								data-config="{&quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]],
								&quot;height&quot;: 200, &quot;toolbar&quot;: &quot;Full&quot;, &quot;skin&quot;: &quot;moono-lisa&quot;,
								&quot;language&quot;: &quot;en-us&quot;, &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;,
								&quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;,
								&quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [ &quot;Table&quot;, &quot;HorizontalRule&quot;],
								[&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;]], &quot;filebrowserWindowHeight&quot;: 725,
								&quot;filebrowserWindowWidth&quot;: 940}"
								data-external-plugin-resources="[]" data-id="id_content" data-type="ckeditortype"> </textarea>
							</div>
							<p>
							<!-- 
							<textarea class="form-control" name="description" rows="10" cols="40" id="id_description" value="" required></textarea></p> -->
							<label for="id_file" class="col-md-2 col-form-label form-control-label">Imagen o Documento Comprobante:</label> <br>
							<input class="form-control" type="file" name="image" id="id_image" /></p>
                            <br>
							<button type="submit" class="save btn btn-default float-right">Enviar datos</button>
							<!-- <input type="submit" name="" value="Send Support Ticket" > -->
						</form>
					</div>
				</div> 
<!-- ENDS FORM -->
			</div>
		</div>
<!-- ENDS SUPPORT -->
	</div>
</div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
<!--
ENDS CONTENT
-->
{% endblock %}