OnlineEXP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from events.views import notes
from user_account.urls import *
# import tinymce
urlpatterns =urlpatterns+ [
path('admin/', admin.site.urls),
path('', include('user_account.urls')),
path('', include('events.urls')),
# path('summernote/', include('django_summernote.urls')),
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'OnlineEXP'

events/urls.py
from django.urls import path, include 
from django.conf.urls import url
from events import views
# todo lo de aqui es tentativo por que quiza no comprendo bien el enlazamiento de las entidades
urlpatterns = [ 
    path('legal/<slug>/', views.legal, name='legal'),
    path('privacy/<slug>/', views.privacy, name='privacy'),

    path('legal/', views.legal, name='legal'),
    path('privacy/', views.privacy, name='privacy'),

    # path('notes/',views.notes,name='notes'),
    # path('notes/<str:title>',views.edit_note,name='notes'), 
    # path('notes/delete/<str:title>',views.delete_note,name='delete_note'), 


    # path('support/', views.support,name='support'),
    # path('event/',views.all_events,name='all_events'),
    # path('event/<str:name_event>/',views.event,name='event'),
    # path('event/unregistry/<str:name_event>', views.unregistry_event, name='unregistry_event'),
    # path('event/join/<str:name_event>', views.join_event, name='join_event'),

    path('event/<str:slug>/', views.see_event, name='see_event'),
    path('event/<str:slug>/support', views.support, name='support'),
    # indica la subvista a usar, room o notes etc...
    # aqui no funciona el generico, no funciona el chat
    # path('event/<str:name_event>/<str:token>', views.event_nested_views, name='event_ne'),

    path('event/programm/<slug>/', views.programa  , name='programa'), 
    path('event/resources/<slug>/', views.recursos  , name='recursos'), 

    # las url de abajo tiene un valor si devuelve todos y dos valores si devuelve un solo room o anuncio
    # es como el get_object y el get_list, se encesitan las url por el parametro
    path('event/room/<slug>/', views.rooms, name='rooms'),

    # principal
    path('event/room/<slug>/<slug_room>', views.room    , name='room'),

    # no funcionan? creo que  por que no existen anuncios
    # path('event/announcements/<str:name_event>/', views.anuncios  , name='anuncios'),
    # path('event/announcements/<str:name_event>/<str:name_ann>/', views.anuncios  , name='anuncios'), 

    path('event/speaker/<slug>/', views.speaker  , name='speakers'), 
    path('event/speaker/<slug>/<slug_speak>/', views.speaker  , name='speakers'), 

    path('event/notes/<slug>/', views.notes  , name='notes'), 
    path('event/notes/<slug>/<str:title>/',views.edit_note,name='notes'), 
    path('event/notes/<slug>/delete/<str:title>/',views.delete_note,name='delete_note'), 


    # esta vista es necesaria para crear los pdfs aunque nunca se acceda a ella!! no borrar!
    path('notes/pdf/<str:title>', views.create_pdf, name='create_pdf'), 
    path('event/<slug>/user-guide', views.user_guide, name='user_guide'), 
    path('event/sponsors/<slug>/', views.sponsors  , name='sponsors'), 
    path('event/peticiones_oracion/<slug>/', views.supportspiritual  , name='supportspiritual'), 
    path('event/teamedition/<slug>/', views.teamedition  , name='teamedition'), 


]

events/models.py
from django.db import models
from django_countries.fields import CountryField
from colorfield.fields import ColorField
from django.utils import timezone
from django.utils.timezone import now
from user_account.models import Code, License
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


class Client(models.Model):
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default='my_name')
    picture = models.FileField(upload_to='pictures/', blank=True, null=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default='my_name')
    client = models.ForeignKey(Client, related_name='event_client', on_delete=models.CASCADE, blank=True,
                               null=True)  # default=1)
    start_date = models.DateField(default=now)
    end_date = models.DateField(default=now)  # date += datetime.timedelta(days=1)
    language = models.CharField(max_length=149, blank=True, null=True)
    country = CountryField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    event_logo = models.FileField(upload_to='pictures/', blank=True, null=True)
    event_banner_1 = models.FileField(upload_to='pictures/', blank=True, null=True)
    event_banner_2 = models.FileField(upload_to='pictures/', blank=True, null=True)
    have_live_player = models.BooleanField(default=False)
    have_chat = models.BooleanField(default=False)
    code = models.ForeignKey(Code, related_name='event_code', on_delete=models.CASCADE, blank=True, null=True,
                             default=None)
    license = models.ForeignKey(License, related_name='event_license', on_delete=models.CASCADE, blank=True, null=True,
                                default=None)

    # colorfield pip install django colorfield

    brand_color_1 = ColorField(default='#6F2EFF')
    brand_color_2 = ColorField(default='#6F2EFF')
    brand_color_3 = ColorField(default='#6F2EFF')

    def _get_unique_slug(self):
        slug_string = self.name
        slug = slugify(slug_string)
        unique_slug = slug
        num = 1
        while Category.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Event_User(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.event.name + '---' + self.user.username)


# class Landing(models.Model):	
# 		client = models.ForeignKey(Event, related_name='landing_event',on_delete=models.CASCADE, blank=True, null=True)#default=1)
# def __str__(self):
# 	return self.name

class LivePlayer(models.Model):
    event = models.ForeignKey(Event, related_name='liveplayer_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    typess = (
        (1, "Live"),
        (2, "SimulatedLive"),
        (3, "VideoPlaceholder"),
    )

    type_video = models.PositiveSmallIntegerField(choices=typess, default=1)
    live_video = models.TextField(blank=True, null=True)
    simulated_live = models.TextField(blank=True, null=True)
    simulated_live_start = models.DateTimeField(default=now)
    simulated_live_ends = models.DateTimeField(default=now)
    placeholder_video = models.TextField(blank=True, null=True)
    use_live_video = models.BooleanField(default=False)
    use_simulated_live = models.BooleanField(default=False)
    use_placeholder_video = models.BooleanField(default=False)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)

    # si necesitas pasar el valor de type_video a los templates usar {instanciaLivePlayer.type_value}
    def type_value(self):
        return dict(LivePlayer.typess)[self.type_video]

    def __str__(self):
        return str(self.event.name + "-" + str(self.type_value()))


class Chat(models.Model):
    event = models.ForeignKey(Event, related_name='chat_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    embed_code = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.event.name


class Schedule(models.Model):
    event = models.ForeignKey(Event, related_name='schedule_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.event.name


class Announcement(models.Model):
    event = models.ForeignKey(Event, related_name='announcement_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    name = models.CharField(max_length=149, unique=True)
    # slug = models.SlugField(max_length=149, default='my_name')
    horizontal_banner = models.FileField(upload_to='pictures/', blank=True, null=True)
    horizontal_banner_title = models.CharField(max_length=149, blank=True, null=True)
    horizontal_banner_link = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    vertical_banner = models.FileField(upload_to='pictures/', blank=True, null=True)
    vertical_banner_title = models.CharField(max_length=149, blank=True, null=True)
    vertical_banner_link = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    link_1 = models.URLField(max_length=200, default='https://google.com')
    link_title_1 = models.CharField(max_length=149, blank=True, null=True)
    link_2 = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    link_title_2 = models.CharField(max_length=149, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    # def _get_unique_slug(self):
    # 	slug_string = self.name
    # 	slug = slugify(slug_string)
    # 	unique_slug = slug
    # 	num = 1
    # 	while Category.objects.filter(slug=unique_slug).exists():
    # 		unique_slug = '{}-{}'.format(slug, num)
    # 		num += 1
    # 	return unique_slug

    # def save(self, *args, **kwargs):
    # 	if not self.slug:
    # 		self.slug = self._get_unique_slug()
    # 	super().save(*args, **kwargs)
    def __str__(self):
        return self.name


class Resource(models.Model):
    event = models.ForeignKey(Event, related_name='resource_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    title = models.CharField(max_length=149, unique=True)
    link = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class Room(models.Model):
    event = models.ForeignKey(Event, related_name='room_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default=None)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)
    banner = models.FileField(upload_to='pictures/', blank=True, null=True)
    icon = models.CharField(max_length=149, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    own_chat = models.BooleanField(default=False)
    own_liveplayer = models.BooleanField(default=False)
    chat = models.TextField(blank=True, null=True)
    live_video = models.TextField(blank=True, null=True)
    simulated_live = models.TextField(blank=True, null=True)
    simulated_live_start = models.DateTimeField(default=now)
    simulated_live_ends = models.DateTimeField(default=now)
    placeholder_video = models.TextField(blank=True, null=True)
    use_live_video = models.BooleanField(default=False)
    use_simulated_live = models.BooleanField(default=False)
    use_placeholder_video = models.BooleanField(default=False)

    def _get_unique_slug(self):
        slug_string = self.name
        slug = slugify(slug_string)
        unique_slug = slug
        num = 1
        while Room.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Speaker(models.Model):
    event = models.ForeignKey(Event, related_name='speaker_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default=None)
    text = models.TextField(blank=True, null=True)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)

    def _get_unique_slug(self):
        slug_string = self.name
        slug = slugify(slug_string)
        unique_slug = slug
        num = 1
        while Speaker.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Video(models.Model):

templates/old/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

templates/old/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}events{% endblock %}</title>
  </head>
  <body>
    <header>
      <h1>My Site</h1>
      <input type=button value="Previous Page" onClick="javascript:history.go(-1);">
        {% if user.is_authenticated %} 
            <li><a href="{% url 'all_events' %}">accede a un evento</a></li> 
            <li><a href="{% url 'logout' %}">logout</a></li>
        {% else %}
            <li><a href="{% url 'login_mail' %}">Login</a></li> 
            <li><a href="{% url 'register_user' %}">Registrate</a></li>
        {% endif %}
      <hr>
    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

templates/old/code_login.html
{% block content %}
<body><h2>ingresa tu codigo</h2>
  datos demo: code:code_event_demo1
  <form method="post">
    {% csrf_token %}
      
      <p>
        <label for="id_username">code:</label><br>
        <input name="username" maxlength="200" required="" id="id_username">
           Required 
      </p>
          <button type="submit">Sign up</button>
  </form>
</body>

{% endblock %}

templates/old/create_profile_code.html
{% block content %}
 {% if error_messages %}
                        <div class="alert alert-danger">
                            <strong>{{ error_messages }}</strong>
                        </div>
              {% endif %}
  <h2>Agrega tu codigo</h2>
  <form method="post">
    {% csrf_token %}
      
      <p>
      ingresa tu codigo proporcionado por el creador del evento para crear tu cuenta:
      <br>
      codigo para testing: code_user_demo1
      <p>
        <label for="id_code">Code:</label><br>
        <input name="code" maxlength="200" required="" id="id_code">
           Required 
      </p>
        
        
      </p>
          <button type="submit">Add code</button>
  </form>
{% endblock %}

templates/old/edit_profile.html
{% extends 'base.html' %}
{% block content %}
 {% if messages %}
                        <div class="alert alert-danger">
                            <strong>{{ messages }}</strong>
                        </div>
              {% endif %}
  <h2>Edit profile</h2>
  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
      
      <p>
        <label for="id_picture">elije una nueva Picture:</label><br>
        <input type="file" name="picture" id="id_picture" value="{{profile.picture}}">
        
        
      </p>
      
      
      <p>
      ingresa un nuevo codigo:
      <p>
        <label for="id_code">Code:</label><br>
        <input name="code" maxlength="200" required="" id="id_code" value="{{profile.code}}"> 
      </p>
        
        
      </p>
          <button type="submit">Edit profile</button>
  </form>
{% endblock %}

templates/old/edit_profile_djangoforms.html
{% block content %}
  <h2>Edit profile</h2>
  <form method="post">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/old/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Pagina de bienvenida</h2>
   {% if user.is_authenticated %}
  <h2>Welcome, {{ user.get_full_name }} <small>{{ user.username }}</small>!</h2>
  <p>Your email address: {{ user.email }}</p>
        {% else %}
          <p>Accede o registrate</p>
        {% endif %}
  
{% endblock %}

templates/old/login.html
{% block content %}
 {% if error_messages %}
                        <div class="alert alert-danger">
                            <strong>{{ error_messages }}</strong>
                        </div>
              {% endif %}
<body><h2>login</h2>
  datos demo: user: test_1 password: Qwerty35$
  <form method="post">
    {% csrf_token %}
      
      <p>
        <label for="id_username">Username:</label><br>
        <input name="username" maxlength="200" required="" id="id_username">
           Required 
      </p>
      
      <p>
        <label for="id_password">Password:</label><br>
        <input type="password" name="password" required="" id="id_password">
        
      <p></p>
          <button type="submit">Sign up</button>
  </form>
</body>

{% endblock %}

templates/old/post.html
{% extends 'base.html' %}

{% block content %}
<h2>Notes</h2>
    <h2>New post</h2>

    <form method="POST" class="post-form">{% csrf_token %}

        <p><label for="id_title">Title:</label> <input type="text" name="title" required maxlength="149" id="id_title"></p>


<!-- aqui inicia el editor de texto, esto lo copie del formulario viendo su codigo en el navegador :v -->
    <script type="text/javascript" src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
    <p><label for="id_content">Content:</label> <div class="django-ckeditor-widget" data-field-id="id_content" style="display: inline-block;">
    <textarea cols="40" id="id_content" name="content" rows="10" required data-processed="0" data-config="{&quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;height&quot;: 291, &quot;toolbar&quot;: &quot;Full&quot;, &quot;skin&quot;: &quot;moono-lisa&quot;, &quot;language&quot;: &quot;en-us&quot;, &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [ &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;width&quot;: 835, &quot;filebrowserWindowHeight&quot;: 725, &quot;filebrowserWindowWidth&quot;: 940}" data-external-plugin-resources="[]" data-id="id_content" data-type="ckeditortype"></textarea>
</div></p>
<!-- aqui termina el editor de texto -->
<form action="{% url 'create_pdf' %}" target="_blank"> 
    	<button type="submit" class="save btn btn-default" >Imprime PDF</button>
    </form>

        <button type="submit" class="save btn btn-default">Guarda nota</button>
    </form>



    <form action="{% url 'create_pdf' %}" target="_blank"> 
    	<button type="submit" class="save btn btn-default" >Imprime PDF</button>
    </form>
{% endblock %}

templates/old/post_djangoforms.html
{% extends 'base.html' %}

{% block content %}
<h2>Notes</h2>
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/old/register.html
{% block content %}
<body><h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
      <p>
        <label for="id_username">Username:</label><br>
        <input type="text" name="username" autofocus="" maxlength="150" required="" id="id_username">
      </p>
      
      <p>
        <label for="id_email">Email:</label><br>
        <input type="email" name="email" maxlength="200" required="" id="id_email">
        
           Required 
        
        
      </p>
      
      <p>
        <label for="id_password1">Password:</label><br>
        <input type="password" name="password1" required="" id="id_password1">
        <ul>

           <li>Your password can't be too similar to your other personal information. </li>
           <li> Your password must contain at least 8 characters</li>
           <li> Your password can't be a commonly used password</li>
           <li> Your password can't be entirely numeric. </li>
           </ul>
        
        
      <p></p>
      
      <p>
        <label for="id_password2">Password confirmation:</label><br>
        <input type="password" name="password2" required="" id="id_password2">
        
           Enter the same password as before, for verification. 
        
        
      </p>
          <button type="submit">Sign up</button>
  </form>
</body>

{% endblock %}
        
        

templates/old/register_djangoform.html
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}    <button type="submit">Sign up</button>
  </form>
{% endblock %}

templates/old/signin.html
{% extends 'base.html' %}
       {% block content %}
{% if error_messages %} 
<div class="alert alert-danger">
    <strong>{{ error_messages }}</strong>
</div>  
{% endif %}
  <h2>registrate</h2>    
    <form method="post" action="{% url 'register_user' %}"> 
      {% csrf_token %}
      
      <p>
        <label for="id_first_name">First name:</label><br>
        <input type="text" name="first_name" id="id_first_name" maxlength="30">
        
        
      </p>
      
      <p>
        <label for="id_last_name">Last name:</label><br>
        <input type="text" name="last_name" id="id_last_name" maxlength="150">
        
        
      </p>
      
      <p>
        <label for="id_email">Email address:</label><br>
        <input type="email" name="email" id="id_email" maxlength="254">
        
        
      </p>
      
      <p>
        <label for="id_password">codigo alpha2020:</label><br>
        <input type="text" name="password" required id="id_password" maxlength="128">
        
        
      </p>
          <button type="submit">Sign up</button>
  </form>
  </div>
{% endblock %}