OnlineEXP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from events.views import notes
from user_account.urls import *
# import tinymce
urlpatterns =urlpatterns+ [
path('admin/', admin.site.urls),
path('', include('user_account.urls')),
path('', include('events.urls')),
# path('summernote/', include('django_summernote.urls')),
]
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'OnlineEXP'

events/urls.py
from django.urls import path, include 
from django.conf.urls import url
from events import views
# todo lo de aqui es tentativo por que quiza no comprendo bien el enlazamiento de las entidades
urlpatterns = [ 
    path('legal/<slug>/', views.legal, name='legal'),
    path('privacy/<slug>/', views.privacy, name='privacy'),

    path('legal/', views.legal, name='legal'),
    path('privacy/', views.privacy, name='privacy'),

    # path('notes/',views.notes,name='notes'),
    # path('notes/<str:title>',views.edit_note,name='notes'), 
    # path('notes/delete/<str:title>',views.delete_note,name='delete_note'), 


    # path('support/', views.support,name='support'),
    # path('event/',views.all_events,name='all_events'),
    # path('event/<str:name_event>/',views.event,name='event'),
    # path('event/unregistry/<str:name_event>', views.unregistry_event, name='unregistry_event'),
    # path('event/join/<str:name_event>', views.join_event, name='join_event'),

    path('event/<str:slug>/', views.see_event, name='see_event'),
    path('event/<str:slug>/support', views.support, name='support'),
    # indica la subvista a usar, room o notes etc...
    # aqui no funciona el generico, no funciona el chat
    # path('event/<str:name_event>/<str:token>', views.event_nested_views, name='event_ne'),

    path('event/programm/<slug>/', views.programa  , name='programa'), 
    path('event/resources/<slug>/', views.recursos  , name='recursos'), 

    # las url de abajo tiene un valor si devuelve todos y dos valores si devuelve un solo room o anuncio
    # es como el get_object y el get_list, se encesitan las url por el parametro
    path('event/room/<slug>/', views.rooms, name='rooms'),

    # principal
    path('event/room/<slug>/<slug_room>', views.room    , name='room'),

    # no funcionan? creo que  por que no existen anuncios
    # path('event/announcements/<str:name_event>/', views.anuncios  , name='anuncios'),
    # path('event/announcements/<str:name_event>/<str:name_ann>/', views.anuncios  , name='anuncios'), 

    path('event/speaker/<slug>/', views.speaker  , name='speakers'), 
    path('event/speaker/<slug>/<slug_speak>/', views.speaker  , name='speakers'), 

    path('event/notes/<slug>/', views.notes  , name='notes'), 
    path('event/notes/<slug>/<str:title>/',views.edit_note,name='notes'), 
    path('event/notes/<slug>/delete/<str:title>/',views.delete_note,name='delete_note'), 


    # esta vista es necesaria para crear los pdfs aunque nunca se acceda a ella!! no borrar!
    path('notes/pdf/<str:title>', views.create_pdf, name='create_pdf'), 
    path('event/<slug>/user-guide', views.user_guide, name='user_guide'), 
    path('event/sponsors/<slug>/', views.sponsors  , name='sponsors'), 
    path('event/peticiones_oracion/<slug>/', views.supportspiritual  , name='supportspiritual'), 
    path('event/teamedition/<slug>/', views.teamedition  , name='teamedition'), 


]

events/models.py
from django.db import models
from django_countries.fields import CountryField
from colorfield.fields import ColorField
from django.utils import timezone
from django.utils.timezone import now
from user_account.models import Code, License
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField


class Client(models.Model):
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default='my_name')
    picture = models.FileField(upload_to='pictures/', blank=True, null=True)

    def __str__(self):
        return self.name


class Event(models.Model):
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default='my_name')
    client = models.ForeignKey(Client, related_name='event_client', on_delete=models.CASCADE, blank=True,
                               null=True)  # default=1)
    start_date = models.DateField(default=now)
    end_date = models.DateField(default=now)  # date += datetime.timedelta(days=1)
    language = models.CharField(max_length=149, blank=True, null=True)
    country = CountryField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    event_logo = models.FileField(upload_to='pictures/', blank=True, null=True)
    event_banner_1 = models.FileField(upload_to='pictures/', blank=True, null=True)
    event_banner_2 = models.FileField(upload_to='pictures/', blank=True, null=True)
    have_live_player = models.BooleanField(default=False)
    have_chat = models.BooleanField(default=False)
    code = models.ForeignKey(Code, related_name='event_code', on_delete=models.CASCADE, blank=True, null=True,
                             default=None)
    license = models.ForeignKey(License, related_name='event_license', on_delete=models.CASCADE, blank=True, null=True,
                                default=None)

    # colorfield pip install django colorfield

    brand_color_1 = ColorField(default='#6F2EFF')
    brand_color_2 = ColorField(default='#6F2EFF')
    brand_color_3 = ColorField(default='#6F2EFF')

    def _get_unique_slug(self):
        slug_string = self.name
        slug = slugify(slug_string)
        unique_slug = slug
        num = 1
        while Category.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Event_User(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.event.name + '---' + self.user.username)


# class Landing(models.Model):	
# 		client = models.ForeignKey(Event, related_name='landing_event',on_delete=models.CASCADE, blank=True, null=True)#default=1)
# def __str__(self):
# 	return self.name

class LivePlayer(models.Model):
    event = models.ForeignKey(Event, related_name='liveplayer_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    typess = (
        (1, "Live"),
        (2, "SimulatedLive"),
        (3, "VideoPlaceholder"),
    )

    type_video = models.PositiveSmallIntegerField(choices=typess, default=1)
    live_video = models.TextField(blank=True, null=True)
    simulated_live = models.TextField(blank=True, null=True)
    simulated_live_start = models.DateTimeField(default=now)
    simulated_live_ends = models.DateTimeField(default=now)
    placeholder_video = models.TextField(blank=True, null=True)
    use_live_video = models.BooleanField(default=False)
    use_simulated_live = models.BooleanField(default=False)
    use_placeholder_video = models.BooleanField(default=False)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)

    # si necesitas pasar el valor de type_video a los templates usar {instanciaLivePlayer.type_value}
    def type_value(self):
        return dict(LivePlayer.typess)[self.type_video]

    def __str__(self):
        return str(self.event.name + "-" + str(self.type_value()))


class Chat(models.Model):
    event = models.ForeignKey(Event, related_name='chat_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    embed_code = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.event.name


class Schedule(models.Model):
    event = models.ForeignKey(Event, related_name='schedule_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.event.name


class Announcement(models.Model):
    event = models.ForeignKey(Event, related_name='announcement_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    name = models.CharField(max_length=149, unique=True)
    # slug = models.SlugField(max_length=149, default='my_name')
    horizontal_banner = models.FileField(upload_to='pictures/', blank=True, null=True)
    horizontal_banner_title = models.CharField(max_length=149, blank=True, null=True)
    horizontal_banner_link = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    vertical_banner = models.FileField(upload_to='pictures/', blank=True, null=True)
    vertical_banner_title = models.CharField(max_length=149, blank=True, null=True)
    vertical_banner_link = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    link_1 = models.URLField(max_length=200, default='https://google.com')
    link_title_1 = models.CharField(max_length=149, blank=True, null=True)
    link_2 = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    link_title_2 = models.CharField(max_length=149, blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    # def _get_unique_slug(self):
    # 	slug_string = self.name
    # 	slug = slugify(slug_string)
    # 	unique_slug = slug
    # 	num = 1
    # 	while Category.objects.filter(slug=unique_slug).exists():
    # 		unique_slug = '{}-{}'.format(slug, num)
    # 		num += 1
    # 	return unique_slug

    # def save(self, *args, **kwargs):
    # 	if not self.slug:
    # 		self.slug = self._get_unique_slug()
    # 	super().save(*args, **kwargs)
    def __str__(self):
        return self.name


class Resource(models.Model):
    event = models.ForeignKey(Event, related_name='resource_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    title = models.CharField(max_length=149, unique=True)
    link = models.URLField(max_length=200, default='https://google.com', blank=True, null=True)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title


class Room(models.Model):
    event = models.ForeignKey(Event, related_name='room_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default=None)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)
    banner = models.FileField(upload_to='pictures/', blank=True, null=True)
    icon = models.CharField(max_length=149, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    own_chat = models.BooleanField(default=False)
    own_liveplayer = models.BooleanField(default=False)
    chat = models.TextField(blank=True, null=True)
    live_video = models.TextField(blank=True, null=True)
    simulated_live = models.TextField(blank=True, null=True)
    simulated_live_start = models.DateTimeField(default=now)
    simulated_live_ends = models.DateTimeField(default=now)
    placeholder_video = models.TextField(blank=True, null=True)
    use_live_video = models.BooleanField(default=False)
    use_simulated_live = models.BooleanField(default=False)
    use_placeholder_video = models.BooleanField(default=False)

    def _get_unique_slug(self):
        slug_string = self.name
        slug = slugify(slug_string)
        unique_slug = slug
        num = 1
        while Room.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Speaker(models.Model):
    event = models.ForeignKey(Event, related_name='speaker_event', on_delete=models.CASCADE, blank=True,
                              null=True)  # default=1)
    name = models.CharField(max_length=149, unique=True)
    slug = models.SlugField(max_length=149, default=None)
    text = models.TextField(blank=True, null=True)
    thumbnail = models.FileField(upload_to='pictures/', blank=True, null=True)

    def _get_unique_slug(self):
        slug_string = self.name
        slug = slugify(slug_string)
        unique_slug = slug
        num = 1
        while Speaker.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Video(models.Model):

events/forms.py
from events.models import *
from django import forms
# class NoteForm(forms.ModelForm):
# 	class Meta:
# 		model = Note
# 		fields ='__all__'
from ckeditor.widgets import CKEditorWidget
class NoteForm(forms.ModelForm):
	text = forms.CharField(widget=CKEditorWidget())
	class Meta:
		model = Note
		fields = '__all__'


from django.contrib.auth.models import User  

 

class SupportForm(forms.ModelForm): 
	# email=forms.CharField(max_length=128,  required=False, widget=forms.EmailInput())
	image=forms.FileField(max_length=128,  required=False, )
	class Meta():

		model = SpiritualSupportRequest
		fields = ('name',"description","image")


# from upload_validator import FileTypeValidator
from django.core.exceptions import ValidationError
def file_size(value):
    limit = 1 * 1024 * 1024
    if value.size > limit:
        raise ValidationError('File too large. Size should not exceed 9 MiB.')


class TeamEditionForm(forms.ModelForm): 
	image=forms.FileField(  required=False)#,  validators=[file_size],)

	class Meta:
		model = Teamedition
		fields=["title","content","image"]
		# fields = '__all__'




# from django_summernote.fields import SummernoteTextFormField, SummernoteTextField

# from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

# # # # Apply summernote to specific fields.
# class NoteForm2(forms.Form):
#     foo = forms.CharField(widget=SummernoteWidget()) 


# class FormFromSomeModel(forms.ModelForm):
#     class Meta:
#         model = SomeModel
#         widgets = {
#             'foo': SummernoteWidget(),
#             'bar': SummernoteInplaceWidget(),
#         }

templates/old/events/all_events.html
{% extends 'base.html' %}
{% block content %} 
<h2>Events disponibles</h2>
los primeros links van al lobby directamente, los segundos van a una ventana con la descripcoion del evento
podrias eliminar los segundos y redirigir todo a see_event, que llevara a la url del loby de los eventos, lo hice para darte opciones por que le cliente parece que no sabia lo que queria 
<ul>
{% if user.is_authenticated %}
mis eventos:
	{% for event_user in my_events%}
		<li> <a href="{% url 'see_event' event_user.event  %}">{{ event_user.event }}</a> <a href="{% url 'unregistry_event' event_user.event  %}">unregistrar</a></li>
	{% endfor %}
	Eventos disponibles
	da click para acceder a cualquier evento

	{% for event in events.all %}
		<li><a href="{% url 'event' event.name  %}">{{ event.name }}</a>  <a href="{% url 'join_event' event.name   %}">unete</a></li></li>
	{% endfor %}
{% else %}
	debes loguearte para acceder a los eventos

	{% for event in events.all %}
		<li><a href="{% url 'login'  %}">{{ event.name }}


		</a></li>
	{% endfor %}
{% endif %}
</ul>
{% endblock %}

templates/old/events/anuncios.html
<p style="background-color:#df9fed;">
	anuncions disponibles para el evento
		<ul> 
	{% for a in announce %}
	evento del chat
	<li> {{ a.event }}  </li>
	texto
	<li> {{ a.name }}  </li>
	horizontal_banner 
		<li> {{ a.name }}  </li>
	horizontal_banner_title 
		<li> {{ a.horizontal_banner_title }}  </li>
	horizontal_banner_link  
		<li> {{ a.horizontal_banner_link }}  </li>
	vertical_banner  
		<li> {{ a.vertical_banner }}  </li>
	vertical_banner_title 
		<li> {{ a.vertical_banner_title }}  </li>
	vertical_banner_link  
		<li> {{ a.vertical_banner_link }}  </li>
	link_1 
		<li> {{ a.link_1 }}  </li>
	link_title_1 
		<li> {{ a.link_title_1 }}  </li>
	link_2 
		<li> {{ a.link_2 }}  </li>
	link_title_2 
		<li> {{ a.link_title_2 }}  </li>
	description 
		<li> {{ a.description }}  </li> 
		{% endfor %}
	</ul> 
	<p>
		
		

templates/old/events/chat.html
<p style="background-color:#b59fed;"> 
	CHAT EXISTENTES EN ESTE EVENTO :
	<ul>
	{% for c in chat%}
	evento del chat
	<li> {{ c.event }}  </li>
	texto
	<li> {{ c.embed_code }}  </li>
		{% endfor %}
	</ul> 
		

	<p>
		
		

templates/old/events/event.html
{% extends 'base.html' %}

{% block content %}
esta vista es forzosa como dummy trap para loguearse por codigos al evento, como sea el evento posee un dummy code :v
<h2>Event: {{ event.name }}</h2>
<ul>
 	<li>slug:{{ event.slug }}</li>
 	<li>client:{{ event.client.name }}</li>
 	<li>description:{{ event.description }}</li>
</ul>
    <h2> <a href="{% url 'join_event' event.name  %}">join</a></li>

{% endblock %}

templates/old/events/join_event.html
{% extends 'events/event.html' %}
{% block content %}
 {% if error_messages %}
                        <div class="alert alert-danger">
                            <strong>{{ error_messages }}</strong>
                        </div>
              {% endif %}
unete al evento {{ event }} ingresando el codigo del evento:

<br>datos demo evento1 codigo:	code_event_demo1
si no tiene codigo usa: CODIGO_MASTER_ONLINEEXP
 <form method="post">
    {% csrf_token %}
      <p>
        <label for="id_code">Code:</label><br>
        <input name="code" maxlength="200" required="" id="id_code">
           Required 
      </p>
      <!-- se que hay formas mas elegantes de pasar este valor pero no se me ocurre al momento una mas que pasar el nombre del evento en un hidden -->
      <input name="event"  value="{{event}}" id="id_event" type="hidden">
          <button type="submit">usuario {{user.username}} unete al evento {{event}}</button>
  </form>
{% endblock %}

templates/old/events/lobby.html
{% extends 'base.html' %}

{% block content %}
videos del evento

<h2>Evento: {{ event.name }}</h2>


<ul>
	datos evento
 	<li>slug:{{ event.slug }}</li>
 	<li>client:{{ event.client.name }}</li>
 	<li>description:{{ event.description }}</li>
</ul>

si no aparece alguno es por que no tiene asociado algun elemento, para iterar usar for y acceder a los elementos de cada tipo
 contexto de emergencia:
 si accedes a este contexto desde otro lugar pues se pierden todos y solo se carga la variable del boton que oprimiste, por ej. notas o rooms
 rooms:{{my_rooms}}
  chat:{{chat}}
 anunciois:{{announce}}
 programas:{{prog}}
 speakers:{{spek}}
 notes:{{notes}}


<!-- aqui van los nombres que les puse en las urls -->
<li><a href="{% url 'programa'  event.name  %}">programa</a></li>
<li><a href="{% url 'room'  event.name   %}">salas</a></li> 
<li><a href="{% url 'speakers'  event.name   %}">speakers</a></li>
<li><a href="{% url 'recursos'  event.name   %}">recursos</a></li>
<li><a href="{% url 'notes'  event.name   %}">notes</a></li>
<li><a href="{% url 'anuncios'  event.name  %}"> anuncios</a></li>





{% include 'events/video.html' %}
{% include 'events/chat.html' %}


{% ifequal token "notes" %}
 {% include 'events/notes.html' %}
{% endifequal %}
{% ifequal token 'anuncios' %}
 {% include 'events/anuncios.html' %}
{% endifequal %}
{% ifequal token 'programa' %}
 {% include 'events/programa.html' %}
{% endifequal %}
{% ifequal token 'recursos' %}
 {% include 'events/recursos.html' %}
{% endifequal %}
{% ifequal token 'room' %}
 {% include 'events/room.html' %}
{% endifequal %}
{% ifequal token 'speakers' %}
 {% include 'events/speakers.html' %}
{% endifequal %}

 
{% endblock %}

templates/old/events/notes.html
{% block content %}

<div style="background-color:#eb969c;"> 
<h2>Notes</h2>
	{% if error_messages %}
		<div class="alert alert-danger">
			<strong>{{ error_messages }}</strong>
		</div>
	{% endif %}
	<ul>
	{% for note in notes.all %}
		<li><a href="{% url 'notes'  event.name  note.title %}">{{ note.title }}</a>  <a href="{% url 'delete_note'  event.name note.title %}">borrar</a>  <a href="{% url 'create_pdf'  note.title %}">imprimir</a></li>

	{% endfor %}
	</ul>
    <h2>New post</h2>
    <form method="POST" class="post-form">
    	{% csrf_token %}


        <p><label for="id_title">Title:</label> 
        	<input type="text" name="title" maxlength="149" id="id_title" required value="{{actual.title}}">
        </p>
	    <script type="text/javascript" src="/static/ckeditor/ckeditor-init.js" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
<script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
    <p><label for="id_text">Text:</label> <div class="django-ckeditor-widget" data-field-id="id_text" style="display: inline-block;">
    <textarea cols="40" id="id_text" name="text" rows="10" required data-processed="0" data-config="{&quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;height&quot;: 291, &quot;toolbar&quot;: &quot;Full&quot;, &quot;skin&quot;: &quot;moono-lisa&quot;, &quot;language&quot;: &quot;en-us&quot;, &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [ &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;width&quot;: 835, &quot;filebrowserWindowHeight&quot;: 725, &quot;filebrowserWindowWidth&quot;: 940}" data-external-plugin-resources="[]" data-id="id_text" data-type="ckeditortype">{{actual.text}}</textarea>
</div>
<p>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

    	<p>
		</div>
{% endblock %}

templates/old/events/programa.html
<p style="background-color:#ed9fbd;">
	programa  de ESTE EVENTO :
	<ul>
	{% for c in program%}
	evento del video
	<li> {{ c.event }}  </li>
	texto
	<li> {{ c.title }}  </li>
	speaker
	<li> {{ c.speaker }}  </li>
	room
	<li> {{ c.room }}  </li>
	start_date
	<li> {{ c.start_date }}  </li>
	end_date
	<li> {{ c.end_date }}  </li>
	video
	<li> {{ c.video }}  </li>
	resource
	<li> {{ c.resource }}  </li>
	thumbnail
	<li> {{ c.thumbnail }}  </li>
	description
	<li> {{ c.description }}  </li>
		{% endfor %}
	</ul> 
 

	<p>
		
		
		

templates/old/events/recursos.html
<p style="background-color:#edb59f;">
	recursos  de ESTE EVENTO :
	<ul>
	{% for c in recursos%}
	<li> {{ c.event }}  </li>
	texto
	<li> {{ c.title }}  </li>
	link
	<li> {{ c.link }}  </li>
	thumbnail
	<li> {{ c.thumbnail }}  </li>
	description
	<li> {{ c.description }}  </li>
		
		{% endfor %}
		


	<p>
		
		

templates/old/events/room.html
<p style="background-color:#ddeb96;">
	todos los room del evento:
	<!-- si necesitas quitar los lives de esta template quita esta parte -->
	LIVES EXISTENTES EN ESTE EVENTO(al aprecer no hay relacion entre lives y rooms):
	<ul>
	{% for live in lives%}
	nombre live 
	<li> {{ live.event }}  </li>
	type live 
	<li> {{ live.live_video }}  </li>
	video live 
	<li> {{ live.live_video }}  </li>
	simulated live 
	<li> {{ live.simmulated_live }}  </li>
	thumbnail
	<li> {{ live.thumbnail }}  </li>
	pre_live_video
	<li> {{ live.pre_live_video }}  </li>

		{% endfor %}
<!-- aqui acaban los lives -->
	<br>
	todas las notas de este usuario:
	si no hay notas pues aqui no aparecera nada :v
	no hay filtro de notas por evento por que no le agregue la FK del evento a la nota, ya esta bastante complicado el crud de notes
	<!-- si necesitas quitar las notas de esta template quita esta parte --> 
<br>
el link del titulo lleva al editor de notas abandonando el room y iendo al url /notes ...
<ul>
	{% for not in notes%}
	titulo nota
	<li>  <a href="{% url 'notes'  event.name  not.title  %}">{{ not.title }}  </a></li>
	texto nota
	<li> {{ not.text }}  </li>
	<a href="{% url 'create_pdf'  not.title %}">imprimir</a></li>
		{% endfor %}
<!-- aqui acaban los lives -->
<br>
<br>
ROOMS EXISTENTES EN ESTE EVENTO:
 	{% for room in my_rooms.all%}

		<li> <a href="{% url 'room'  event.name room.name  %}"> link al room {{ room.event }} </a>  </li>
		<li> datos del room llamado {{ room.event }}  </li>
		<li>  {{ room.name }}  </li>
		thumb:
		<li>  {{ room.thumbnai }}  </li>
		banner:
		<li>  {{ room.banner }}  </li>
		icon:
		<li>  {{ room.icon }}  </li>
		descripcion:
		<li>   {{ room.description }}  </li>
		tiene live_player:
		<li>   {{ room.own_liveplayer }}  </li>
		supongo que tu reproductor pregutara si las siguientes condiciones son false o true
		tiene chat:
		<li>  {{ room.own_chat }}  </li>
		liveplayer:
		<li>  {{ room.live_video }}  </li>
		chat:
		<li>  {{ room.chat }}  </li>

	{% endfor %}
</ul>
	<p>
		
		

templates/old/events/speakers.html
<p style="background-color:#edb59f;">
	speakers  de ESTE EVENTO :
	<ul>
	{% for c in speakers%}
	<li><a href="{% url 'speakers'  event.name c.name  %}">  {{ c.name }}  </a></li>
	evento
	<li> {{ c.event }}  </li>
	text
	<li> {{ c.text }}  </li>
	thumbnail
	<li> {{ c.thumbnail }}  </li> 
		
		{% endfor %}

	<p>
		
		

templates/old/events/video.html
<p style="background-color:#9fedb4;">
	LIVES EXISTENTES EN ESTE EVENTO :
	<ul>
	{% for live in lives%}
	nombre live 
	<li> {{ live.event }}  </li>
	type live 
	<li> {{ live.live_video }}  </li>
	video live 
	<li> {{ live.live_video }}  </li>
	simulated live 
	<li> {{ live.simmulated_live }}  </li>
	thumbnail
	<li> {{ live.thumbnail }}  </li>
	pre_live_video
	<li> {{ live.pre_live_video }}  </li>

		{% endfor %}
	</ul>
	<p>
		